-- PRISM PULSE: GLOBAL SECTOR INITIALIZATION (v2 - Fixed Policies)
-- Run this in your Supabase SQL Editor to build the leaderboard system.

-- 1. Create Profiles (User Identities)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  nickname text unique,
  avatar_url text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Create Scores (The Hall of Fame)
create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  mode text not null,      -- 'classic', 'blitz', 'bomb'
  platform text not null,  -- 'ios', 'android'
  score integer default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, mode)    -- Ensures one world record per mode per user
);

-- 3. Enable Security (RLS)
alter table public.profiles enable row level security;
alter table public.scores enable row level security;

-- 4. Rules of Engagement (Policies)
-- Allow anyone to see the leaderboards
drop policy if exists "Scores are public" on public.scores;
create policy "Scores are public" on public.scores for select using (true);

drop policy if exists "Profiles are public" on public.profiles;
create policy "Profiles are public" on public.profiles for select using (true);

-- Allow authenticated users to manage their own data
-- In Postgres, upsert is handled by combining INSERT and UPDATE policies
drop policy if exists "Users can insert their own score" on public.scores;
create policy "Users can insert their own score" on public.scores for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update their own score" on public.scores;
create policy "Users can update their own score" on public.scores for update using (auth.uid() = user_id);

drop policy if exists "Users can manage their own profile" on public.profiles;
create policy "Users can manage their own profile" on public.profiles for all using (auth.uid() = id);

-- 5. Automate Updates
-- This ensures the 'updated_at' timestamp changes when records are modified
create or replace function handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists on_profile_update on public.profiles;
create trigger on_profile_update
  before update on public.profiles
  for each row execute procedure handle_updated_at();

drop trigger if exists on_score_update on public.scores;
create trigger on_score_update
  before update on public.scores
  for each row execute procedure handle_updated_at();